"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], pick=a=>a[Math.floor(Math.random()*a.length)], title=s=>s?`${s[0].toUpperCase()}${s.slice(1).toLowerCase()}`:"";
const DATA={
first:["Alden","Alina","Amara","Arden","Aria","Asher","Brenna","Caleb","Cassian","Clara","Corin","Dahlia","Dorian","Edwin","Elara","Elias","Elise","Emmett","Evelyn","Felix","Freya","Gareth","Gavin","Gemma","Gideon","Hazel","Helena","Henry","Iris","Isla","Jasper","Jonas","Julian","Kaia","Kieran","Lena","Leo","Liam","Lila","Lucian","Maeve","Mara","Mason","Mira","Nadia","Nolan","Nora","Owen","Quinn","Rhea","Ronan","Rowan","Selene","Silas","Soren","Stella","Talia","Theo","Vera","Wren"],
last:["Ashford","Blackwood","Brightwood","Carter","Dawson","Emberfall","Frost","Gray","Green","Hale","Hawthorne","Hill","Ironwood","Johnson","King","Lewis","Marsh","Moore","Morgan","Nightbrook","Parker","Reed","Rivers","Rowe","Silver","Smith","Stone","Storm","Taylor","Thorne","Vale","Walker","Ward","White","Williams","Wilson","Wood","Wright"],
dndRaces:["Human","Elf","Dwarf","Halfling","Gnome","Tiefling","Dragonborn","Half-Orc"], classes:["Barbarian","Bard","Cleric","Druid","Fighter","Monk","Paladin","Ranger","Rogue","Sorcerer","Warlock","Wizard"],
skyrimRaces:["Nord","Breton","Imperial","Redguard","High Elf","Wood Elf","Dark Elf","Orc","Khajiit","Argonian"], archetypes:["Warrior","Mage","Thief","Assassin","Companion","Dragonborn","Vampire Hunter","Necromancer","Knight","Ranger"],
traits:["careful and observant","boisterous but loyal","quietly compassionate","suspicious of strangers","curious to a fault","dry-witted and practical","formal and exacting","recklessly generous","patient until provoked","charming but evasive"],
goals:["restore the family reputation","find a missing sibling","repay an impossible debt","map an uncharted ruin","protect a threatened community","recover a stolen relic","prove an old legend true","break a dangerous curse","earn a place among local heroes","expose a powerful fraud"],
secrets:["once served the enemy","carries a falsified identity","knows the location of a forbidden vault","is protecting the real culprit","owes a favor to a thieves' guild","can hear a mysterious voice in dreams","is heir to a forgotten title","accidentally awakened an ancient threat","possesses a dangerous map","has met the villain before"],
origins:["a crowded river port","a remote mountain village","a respected merchant household","a traveling theater company","an isolated forest enclave","a military border town","a monastery built over old ruins","a farming community near a haunted wood","the lower district of a great city","a nomadic caravan"],
turns:["survived a raid that destroyed their home","was framed for a crime they did not commit","discovered unexpected magical talent","saved a stranger who later became a mentor","found a coded journal among family belongings","refused an order that would have harmed innocents","lost a prized possession to a rival","witnessed something no one else believed","inherited a duty they never wanted","made a bargain whose cost is still unclear"],
fears:["being forgotten","failing those who depend on them","deep water","losing control of their power","becoming like an estranged parent","public disgrace","undead creatures","being trapped underground","betrayal by a close ally","the consequences of an old promise"],
flaws:["cannot walk away from a challenge","trusts charm too easily","keeps dangerous secrets","mistakes stubbornness for courage","holds grudges","overplans simple problems","takes needless risks for praise","refuses help until it is too late","is easily distracted by mysteries","judges others too quickly"],
professions:["apothecary","blacksmith","caravan guard","cartographer","cook","courier","dockworker","herbalist","innkeeper","librarian","merchant","miller","scribe","stablehand","tailor","tinker","watch officer"],
alignments:["Lawful Good","Neutral Good","Chaotic Good","Lawful Neutral","True Neutral","Chaotic Neutral","Lawful Evil","Neutral Evil","Chaotic Evil"],
objectives:["recover a relic before a rival faction does","escort a nervous scholar through dangerous territory","investigate disappearances near an abandoned shrine","break a curse afflicting a local family","rescue captives from a hidden stronghold","deliver a sealed object without opening it","identify the creature poisoning the water supply","negotiate peace between feuding settlements","stop a ritual before the next full moon","locate a missing expedition"],
locations:["a flooded dwarven mine","a ruined hilltop observatory","catacombs beneath the market district","a forest where paths change overnight","a fortress trapped in permanent winter","an abandoned coastal village","a buried temple beneath farmland","a canyon crossed by ancient rope bridges","a manor surrounded by unnatural fog","a volcanic cavern filled with glass"],
villains:["a disgraced knight","a patient necromancer","a shapechanging spy","a merchant prince with hired blades","a cult leader claiming divine authority","an exiled mage","a corrupted forest guardian","an ambitious crime boss","a warlord seeking legitimacy","a scholar possessed by an artifact"],
complications:["the patron withheld a crucial fact","the apparent villain is protecting someone","another party has the same objective","the reward is stolen before payment","the location is slowly collapsing","a trusted guide changes sides","the target is willing to cooperate for a price","the threat returns stronger each night","the law considers the party trespassers","success will anger a powerful faction"],
rewards:["a chest of gold and a land grant","a rare enchanted weapon","access to a restricted library","a favor from a noble house","ownership of a small property","a map to another lost site","a magical charm with one remaining charge","guild membership and safe lodging","forgiven debts and public recognition","information about a personal mystery"],
placeTypes:["Tavern","Inn","Blacksmith","General Store","Magic Shop","Apothecary","Bookshop","Temple","Stable","Tailor","Jeweler","Bakery","Market Stall","Guild Hall","Bathhouse","Curiosity Shop","Caravan Office","Adventuring Supply Store"],
placeAdj:["Copper","Crowned","Dancing","Emerald","Golden","Laughing","Moonlit","Old","Painted","Red","Restless","Silver","Sleeping","Three","Wandering"], placeNoun:["Anvil","Badger","Boar","Candle","Cask","Dragon","Fox","Griffin","Lantern","Lion","Magpie","Oak","Owl","Stag","Wyvern"],
atmospheres:["warm, noisy, and welcoming","orderly and expensive","small but immaculately kept","crowded with travelers","dimly lit and full of private booths","bright, colorful, and slightly chaotic","quiet enough to hear every whisper","decorated with trophies from distant lands","busy with apprentices and deliveries","old-fashioned but trusted by locals"],
specialties:["custom commissions completed unusually quickly","rare imports acquired through questionable contacts","honest prices and stern service","a signature item known across the region","repairs no competitor will attempt","discreet service for unusual customers","locally sourced goods of exceptional quality","a hidden menu available by password","free advice with every purchase","items made from salvaged monster parts"],
rumors:["a sealed cellar door opens by itself at midnight","one employee is secretly a retired adventurer","a regular customer pays with coins from a vanished kingdom","a tunnel under the building reaches the old walls","the owner possesses a map they refuse to sell","someone has been replacing inventory with perfect copies","a ghost leaves warnings in spilled flour","a hidden room hosts forbidden auctions","the business was won in a card game","a noble visits in disguise every seventh night"],
partyTypes:["Adventuring Company","Mercenary Band","Holy Order","Exploration Guild","Monster Hunters","Rebel Cell","Mage Circle"], partyAdj:["Ashen","Broken","Crimson","Emerald","Golden","Last","Silent","Silver","Stormbound","Wandering"], partyNoun:["Arrows","Banners","Blades","Compasses","Crowns","Griffons","Lanterns","Ravens","Shields","Stars","Wolves"],
weaponTypes:["Dagger","Sword","War Axe","Mace","Greatsword","Battleaxe","Warhammer","Bow","Staff"], materials:["Iron","Steel","Dwarven","Elven","Orcish","Glass","Ebony","Daedric","Dragonbone"], enchants:["Burns targets with searing flame","Freezes targets and drains stamina","Shocks targets and damages magicka","Absorbs health","Absorbs stamina","Captures souls","Fills targets with fear","Paralyzes targets briefly","Banishes summoned creatures","Deals additional damage to undead"], weaponA:["Ash","Blood","Dawn","Doom","Dragon","Ember","Frost","Grave","Moon","Night","Oath","Shadow","Sky","Soul","Storm"], weaponB:["Bane","Bite","Brand","Cleaver","Edge","Fang","Reaver","Song","Spite","Talons","Whisper","Wrath"]};

function options(a){return a.map(x=>`<option>${x}</option>`).join("")}
function seedName(){return `${pick(DATA.first)} ${pick(DATA.last)}`}
function fantasyName(game,input=""){
 const words=(input.trim()||seedName()).split(/\s+/), race=game==="dnd"?pick(DATA.dndRaces):pick(DATA.skyrimRaces);
 const pre=game==="dnd"?["Al","Bel","Cor","Dra","Ela","Fae","Gar","Khar","Mor","Syl","Tha","Val"]:["Ael","Brynj","Dar","Eir","Fal","Hjal","J'","Khar","Nel","Ra'","Sven","Tor"];
 const suf=game==="dnd"?["ael","an","ard","iel","or","ric","thir","wyn"]:["ar","eif","eth","ion","olf","rik","var","yn"];
 return {name:words.map((w,i)=>title(i?`${w.slice(0,3)}${pick(suf)}`:`${pick(pre)}${w.slice(0,4)}`)).join(" "),race,seed:words.join(" ")};
}
function field(label,value,key,full=false,extra=""){return `<div class="sheet-field ${full?'full':''}" data-key="${key}"><span class="label">${label}</span><div class="value">${value}</div><button class="reroll" data-reroll="${key}" title="Reroll ${label}">↻</button>${extra}</div>`}
function sheet(titleText,fields,copyText){return `<section class="sheet"><div class="sheet-head"><h3>${titleText}</h3><button class="btn" data-copy>Copy sheet</button></div><div class="sheet-grid">${fields.join("")}</div><textarea class="copy-source hidden">${copyText}</textarea></section>`}
function copyText(obj,heading){return [heading,...Object.entries(obj).map(([k,v])=>`\n${k.toUpperCase()}\n${v}`)].join("\n")}
function setupTool(id,titleText,sub,controls,generate){const node=document.getElementById(id);node.innerHTML=`<h2 class="panel-title">${titleText}</h2><p class="panel-subtitle">${sub}</p>${controls}<div class="actions"><button class="btn primary" data-generate>Generate</button></div><div class="output"></div>`;node.querySelector("[data-generate]").onclick=()=>generate(node);generate(node)}
function bind(node,generateField){node.querySelectorAll("[data-reroll]").forEach(b=>b.onclick=()=>generateField(b.dataset.reroll));node.querySelector("[data-copy]")?.addEventListener("click",async e=>{const t=node.querySelector(".copy-source").value;try{await navigator.clipboard.writeText(t)}catch{const a=node.querySelector(".copy-source");a.classList.remove("hidden");a.select();document.execCommand("copy");a.classList.add("hidden")}e.currentTarget.textContent="Copied";setTimeout(()=>e.currentTarget.textContent="Copy sheet",1000)})}
function renderState(node,titleText,state,labels,reroll,extras={}){const fields=Object.keys(state).map(k=>field(labels[k]||k,state[k],k,extras[k]?.full,extras[k]?.html||""));node.querySelector(".output").innerHTML=sheet(titleText,fields,copyText(Object.fromEntries(Object.keys(state).map(k=>[labels[k]||k,state[k]])),titleText));bind(node,reroll)}

function nameTool(id,game){setupTool(id,game==="dnd"?"D&D Character Name":"Skyrim Character Name","Transform an entered name, or leave it blank for a random seed.",`<div class="controls"><label class="field wide">Original name<input data-input placeholder="Optional: first, middle, and last names"></label><label class="field">Style<select data-style><option>Short</option><option selected>Normal</option><option>Epic</option></select></label></div>`,node=>{let state={};const make=()=>{const n=fantasyName(game,node.querySelector("[data-input]").value);state={Name:n.name,Race:n.race,Style:node.querySelector("[data-style]").value,Seed:n.seed};draw()};const draw=()=>renderState(node,state.Name,state,{Name:"Name",Race:"Race",Style:"Style",Seed:"Original / random seed"},k=>{if(k==="Name"||k==="Seed")make();else if(k==="Race"){state.Race=game==="dnd"?pick(DATA.dndRaces):pick(DATA.skyrimRaces);draw()}else{state.Style=pick(["Short","Normal","Epic"]);draw()}});make()})}

function makeNPC(base={}){const n=fantasyName("dnd",base.name||"");return {Name:base.name||n.name,Race:base.race||n.race,Class:base.class||pick(DATA.classes),Level:String(Math.floor(Math.random()*12)+1),Alignment:pick(DATA.alignments),Profession:base.profession||pick(DATA.professions),Trait:pick(DATA.traits),Origin:pick(DATA.origins),Goal:pick(DATA.goals),Secret:pick(DATA.secrets),Fear:pick(DATA.fears),Flaw:pick(DATA.flaws)}}
let pendingNPC=null;
function npcTool(){setupTool("npc","NPC Generator","Create a character-sheet-style NPC. Place owners, workers, and quest contacts can be sent here.",`<div class="controls"><label class="field">Race<select data-race><option>Random</option>${options(DATA.dndRaces)}</select></label><label class="field">Class<select data-class><option>Random</option>${options(DATA.classes)}</select></label><label class="field">Level range<select data-level><option>1–4</option><option selected>1–12</option><option>5–15</option></select></label></div>`,node=>{let state=pendingNPC||makeNPC();pendingNPC=null;const draw=()=>renderState(node,state,state.Name,state,k=>k==="Name"?"Name":k,r=>{const fresh=makeNPC({name:r==="Name"?"":state.Name,race:state.Race,class:state.Class,profession:state.Profession});state[r]=fresh[r];draw()},{Origin:{full:true},Goal:{full:true},Secret:{full:true}});draw()})}
function backstoryTool(){setupTool("backstory","Character Backstory Generator","Build a structured origin for a D&D character.",`<div class="controls"><label class="field wide">Character name<input data-name placeholder="Optional"></label><label class="field">Race<select data-race><option>Random</option>${options(DATA.dndRaces)}</select></label><label class="field">Class<select data-class><option>Random</option>${options(DATA.classes)}</select></label></div>`,node=>{let state={};const make=()=>{const nm=node.querySelector("[data-name]").value.trim()||fantasyName("dnd").name;state={Name:nm,Race:pick(DATA.dndRaces),Class:pick(DATA.classes),Origin:pick(DATA.origins),TurningPoint:pick(DATA.turns),Goal:pick(DATA.goals),Fear:pick(DATA.fears),Flaw:pick(DATA.flaws),Secret:pick(DATA.secrets)};draw()};const draw=()=>renderState(node,state,`${state.Name} • Backstory`,state,{TurningPoint:"Turning point"},k=>{if(k==="Name")state.Name=fantasyName("dnd").name;else if(k==="Race")state.Race=pick(DATA.dndRaces);else if(k==="Class")state.Class=pick(DATA.classes);else state[k]=pick({Origin:DATA.origins,TurningPoint:DATA.turns,Goal:DATA.goals,Fear:DATA.fears,Flaw:DATA.flaws,Secret:DATA.secrets}[k]);draw()},{Origin:{full:true},TurningPoint:{full:true},Goal:{full:true},Secret:{full:true}});make()})}
function questTool(){
  setupTool("quest","Quest Generator","Create a complete quest and turn the quest giver into a reusable NPC.",`<div class="controls"><label class="field">Scope<select data-scope><option>Local problem</option><option>Regional threat</option><option>Epic mission</option></select></label></div>`,node=>{
    let state={};
    const make=()=>{
      node._contact=makeNPC();
      state={Title:`The ${pick(DATA.placeAdj)} ${pick(["Relic","Road","Oath","Vault","Shadow","Crown"])}`,Objective:pick(DATA.objectives),Location:pick(DATA.locations),Villain:pick(DATA.villains),Complication:pick(DATA.complications),Reward:pick(DATA.rewards),QuestGiver:node._contact.Name,QuestGiverRole:node._contact.Profession};
      draw();
    };
    const draw=()=>{
      const reroll=k=>{
        if(k==="Title") state.Title=`The ${pick(DATA.placeAdj)} ${pick(["Relic","Road","Oath","Vault","Shadow","Crown"])}`;
        else if(k==="QuestGiver"||k==="QuestGiverRole"){
          node._contact=makeNPC(); state.QuestGiver=node._contact.Name; state.QuestGiverRole=node._contact.Profession;
        } else state[k]=pick({Objective:DATA.objectives,Location:DATA.locations,Villain:DATA.villains,Complication:DATA.complications,Reward:DATA.rewards}[k]);
        draw();
      };
      renderState(node,state.Title,state,{QuestGiver:"Quest giver",QuestGiverRole:"Quest giver role"},reroll,{Objective:{full:true},Complication:{full:true},QuestGiver:{html:`<button class="inline-action" data-send-npc>Generate NPC backstory</button>`}});
      node.querySelector("[data-send-npc]").onclick=()=>sendNPC(node._contact);
    };
    make();
  });
}
function placeTool(){
  setupTool("place","Place Generator","Generate taverns, stores, guilds, temples, and other businesses, including staff who can become full NPCs.",`<div class="controls"><label class="field">Place type<select data-type><option>Random</option>${options(DATA.placeTypes)}</select></label><label class="field">Workers<select data-workers><option>1</option><option selected>2</option><option>3</option><option>4</option></select></label></div>`,node=>{
    let state={},staff=[];
    const make=()=>{
      const choice=node.querySelector("[data-type]").value;
      const type=choice==="Random"?pick(DATA.placeTypes):choice;
      const count=+node.querySelector("[data-workers]").value;
      staff=Array.from({length:count},(_,i)=>makeNPC({profession:i===0?`${type} owner`:pick(DATA.professions)}));
      state={Name:`The ${pick(DATA.placeAdj)} ${pick(DATA.placeNoun)}`,Type:type,Atmosphere:pick(DATA.atmospheres),Specialty:pick(DATA.specialties),Rumor:pick(DATA.rumors),Owner:staff[0].Name,Workers:staff.slice(1).map(x=>`${x.Name} • ${x.Profession}`).join("\n")||"None"};
      draw();
    };
    const draw=()=>{
      const reroll=k=>{
        if(k==="Name") state.Name=`The ${pick(DATA.placeAdj)} ${pick(DATA.placeNoun)}`;
        else if(k==="Type") state.Type=pick(DATA.placeTypes);
        else if(k==="Owner"||k==="Workers"){
          staff=staff.map((x,i)=>i===0?makeNPC({profession:`${state.Type} owner`}):makeNPC());
          state.Owner=staff[0].Name;
          state.Workers=staff.slice(1).map(x=>`${x.Name} • ${x.Profession}`).join("\n")||"None";
        } else state[k]=pick({Atmosphere:DATA.atmospheres,Specialty:DATA.specialties,Rumor:DATA.rumors}[k]);
        draw();
      };
      renderState(node,state.Name,state,{},reroll,{Atmosphere:{full:true},Specialty:{full:true},Rumor:{full:true},Owner:{html:`<button class="inline-action" data-owner>Generate owner NPC</button>`},Workers:{full:true,html:`<div class="worker-buttons"></div>`}});
      node.querySelector("[data-owner]").onclick=()=>sendNPC(staff[0]);
      const box=node.querySelector(".worker-buttons");
      staff.slice(1).forEach((w,i)=>{const b=document.createElement("button");b.className="inline-action";b.textContent=`Generate ${w.Name}`;b.onclick=()=>sendNPC(staff[i+1]);box.appendChild(b)});
    };
    make();
  });
}
function partyTool(){setupTool("party","D&D Party Name Generator","Create a party, guild, order, or adventuring-company name.",`<div class="controls"><label class="field">Party type<select data-type>${options(DATA.partyTypes)}</select></label></div>`,node=>{let state={};const make=()=>{state={Name:`The ${pick(DATA.partyAdj)} ${pick(DATA.partyNoun)}`,Type:pick(DATA.partyTypes),Motto:pick(["No road untraveled.","Together against the dark.","Fortune favors the prepared.","By oath and iron.","We return with the answer.","None are left behind."])};draw()};const draw=()=>renderState(node,state,state.Name,state,{},k=>{if(k==="Name")state.Name=`The ${pick(DATA.partyAdj)} ${pick(DATA.partyNoun)}`;else if(k==="Type")state.Type=pick(DATA.partyTypes);else state.Motto=pick(["No road untraveled.","Together against the dark.","Fortune favors the prepared.","By oath and iron.","We return with the answer.","None are left behind."]);draw()});make()})}
function dndWeaponTool(){
  const types=["Club","Dagger","Greatclub","Handaxe","Javelin","Light Hammer","Mace","Quarterstaff","Sickle","Spear","Light Crossbow","Dart","Shortbow","Sling","Battleaxe","Flail","Glaive","Greataxe","Greatsword","Halberd","Lance","Longsword","Maul","Morningstar","Pike","Rapier","Scimitar","Shortsword","Trident","War Pick","Warhammer","Whip","Blowgun","Hand Crossbow","Heavy Crossbow","Longbow"];
  const rarities=["Common","Uncommon","Rare","Very Rare","Legendary"];
  const properties=["Finesse","Heavy","Light","Reach","Thrown","Two-Handed","Versatile","Ammunition"];
  const effects=["glows near hidden doors","deals extra radiant damage to undead","returns to the wielder when thrown","can cast a protective ward once per day","ignores resistance to one chosen damage type","grants advantage on initiative rolls","creates a burst of thunder on a critical hit","marks a struck enemy with pale fire","allows the wielder to understand one ancient language","can cut through nonmagical restraints instantly","stores one spell of 3rd level or lower","emits bright light on command"];
  const quirks=["hums when danger is near","refuses to remain dirty","displays a new rune after every victory","is warm to the touch in moonlight","whispers the name of its first owner","casts no reflection","smells faintly of rain","becomes heavier in the hands of a coward","rings softly when a lie is spoken nearby","has a pommel shaped like a watchful eye"];
  const histories=["forged for a border commander whose name was erased from official records","recovered from a sealed chamber beneath a ruined keep","carried by a monster hunter who vanished during a winter expedition","created by a guild that no longer appears on any map","presented as a peace offering before a famous betrayal","found embedded in a stone at the center of an abandoned village","passed through generations of an adventuring family","crafted from metal recovered after a falling star"];
  setupTool("dnd-weapon","D&D Weapon Generator","Create a named weapon with type, rarity, magical effect, quirk, and history.",`<div class="controls"><label class="field">Weapon type<select data-type><option>Random</option>${options(types)}</select></label><label class="field">Rarity<select data-rarity><option>Random</option>${options(rarities)}</select></label></div>`,node=>{
    let state={};
    const make=()=>{const ty=node.querySelector("[data-type]").value,ra=node.querySelector("[data-rarity]").value;state={Name:`${pick(DATA.weaponA)}${pick(DATA.weaponB)}`,Type:ty==="Random"?pick(types):ty,Rarity:ra==="Random"?pick(rarities):ra,Property:pick(properties),Effect:pick(effects),Quirk:pick(quirks),History:pick(histories)};draw()};
    const draw=()=>renderState(node,state,state.Name,state,{},k=>{if(k==="Name")state.Name=`${pick(DATA.weaponA)}${pick(DATA.weaponB)}`;else if(k==="Type")state.Type=pick(types);else if(k==="Rarity")state.Rarity=pick(rarities);else state[k]=pick({Property:properties,Effect:effects,Quirk:quirks,History:histories}[k]);draw()},{Effect:{full:true},Quirk:{full:true},History:{full:true}});
    make();
  });
}

function dndItemTool(){
  const categories=["Armor","Potion","Ring","Rod","Scroll","Staff","Wand","Wondrous Item","Adventuring Gear","Instrument","Tool","Container","Clothing","Charm"];
  const rarities=["Common","Uncommon","Rare","Very Rare","Legendary"];
  const forms=["Amulet","Belt","Boots","Bottle","Bracelet","Brooch","Candle","Cape","Carved Stone","Circlet","Coin","Crown","Gloves","Goggles","Lantern","Mask","Mirror","Orb","Pendant","Quill","Rope","Satchel","Tome","Totem"];
  const powers=["reveals invisible writing","creates a small extradimensional storage space","allows brief communication with animals","protects its bearer from extreme temperatures","changes color in the presence of poison","casts a convincing minor illusion","restores a small amount of vitality once per day","lets its bearer breathe underwater for a short time","points toward the nearest safe shelter","records the last minute of nearby sound","repairs a damaged mundane object each dawn","grants darkvision for one hour","opens one nonmagical lock before becoming dormant","produces enough food for one person each day"];
  const drawbacks=["attracts curious moths after sunset","occasionally speaks in its creator's voice","cannot cross running water unless wrapped in cloth","becomes cold whenever its power is used","must be complimented before it functions","leaves a faint trail of glittering dust","causes the bearer to dream of an unknown city","works only when no one is watching","temporarily changes the bearer's hair color","refuses to function for anyone who breaks a promise"];
  const appearances=["etched with interlocking silver runes","made from dark wood with brass fittings","wrapped in faded blue silk","shaped like a tiny sleeping dragon","inlaid with cloudy green crystal","plain except for a single red thread","decorated with stars that subtly shift position","carved from ivory-colored stone","patched together from several different materials","polished so perfectly that it never gathers dust"];
  setupTool("dnd-item","D&D Magic Item Generator","Generate magic items with category, rarity, appearance, power, drawback, and origin.",`<div class="controls"><label class="field">Category<select data-category><option>Random</option>${options(categories)}</select></label><label class="field">Rarity<select data-rarity><option>Random</option>${options(rarities)}</select></label></div>`,node=>{
    let state={};
    const make=()=>{const ca=node.querySelector("[data-category]").value,ra=node.querySelector("[data-rarity]").value;state={Name:`${pick(DATA.placeAdj)} ${pick(forms)}`,Category:ca==="Random"?pick(categories):ca,Rarity:ra==="Random"?pick(rarities):ra,Appearance:pick(appearances),Power:pick(powers),Drawback:pick(drawbacks),Origin:pick(DATA.origins)};draw()};
    const draw=()=>renderState(node,state,state.Name,state,{},k=>{if(k==="Name")state.Name=`${pick(DATA.placeAdj)} ${pick(forms)}`;else if(k==="Category")state.Category=pick(categories);else if(k==="Rarity")state.Rarity=pick(rarities);else state[k]=pick({Appearance:appearances,Power:powers,Drawback:drawbacks,Origin:DATA.origins}[k]);draw()},{Appearance:{full:true},Power:{full:true},Drawback:{full:true},Origin:{full:true}});
    make();
  });
}

function weaponTool(){setupTool("weapon","Skyrim Weapon Name Generator","Create a lore-friendly weapon name, material, type, enchantment, and history.",`<div class="controls"><label class="field">Weapon type<select data-type><option>Random</option>${options(DATA.weaponTypes)}</select></label><label class="field">Material<select data-material><option>Random</option>${options(DATA.materials)}</select></label></div>`,node=>{let state={};const make=()=>{const t=node.querySelector("[data-type]").value,m=node.querySelector("[data-material]").value;state={Name:`${pick(DATA.weaponA)}${pick(DATA.weaponB)}`,Type:t==="Random"?pick(DATA.weaponTypes):t,Material:m==="Random"?pick(DATA.materials):m,Enchantment:pick(DATA.enchants),History:pick(["Forged for a forgotten jarl and lost in a barrow.","Carried by a mercenary who vanished near the Pale.","Recovered from a sealed chamber beneath an old fort.","Made by a reclusive smith who accepted no coin.","Its previous owner appears in no surviving record.","Legends claim it was quenched in water from Blackreach."])};draw()};const draw=()=>renderState(node,state,state.Name,state,{},k=>{if(k==="Name")state.Name=`${pick(DATA.weaponA)}${pick(DATA.weaponB)}`;else if(k==="Type")state.Type=pick(DATA.weaponTypes);else if(k==="Material")state.Material=pick(DATA.materials);else if(k==="Enchantment")state.Enchantment=pick(DATA.enchants);else state.History=pick(["Forged for a forgotten jarl and lost in a barrow.","Carried by a mercenary who vanished near the Pale.","Recovered from a sealed chamber beneath an old fort.","Made by a reclusive smith who accepted no coin.","Its previous owner appears in no surviving record.","Legends claim it was quenched in water from Blackreach."]);draw()},{History:{full:true}});make()})}
function sendNPC(npc){pendingNPC=npc;document.querySelector('[data-game="dnd"]').click();document.querySelector('[data-tool="npc"]').click();document.querySelector('#npc [data-generate]').click();document.getElementById("npc").scrollIntoView({behavior:"smooth"})}
$$('.game-tab').forEach(b=>b.onclick=()=>{$$('.game-tab,.game-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.game).classList.add('active')});
$$('.tool-tab').forEach(b=>b.onclick=()=>{const parent=b.closest('.game-panel');parent.querySelectorAll('.tool-tab,.tool-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tool).classList.add('active')});
nameTool("dnd-name","dnd");backstoryTool();questTool();placeTool();partyTool();npcTool();dndWeaponTool();dndItemTool();nameTool("skyrim-name","skyrim");weaponTool();
